workspace 'RHLANServer'
project 'RHLANServer.xcodeproj'

target 'RHLANServer' do
	platform :ios, '8.0'
	project 'RHLANServer.xcodeproj'
	pod 'RHSocketKit/Extend', '~> 2.2.3.1'
	pod 'libextobjc/EXTScope', '~> 0.4.1'
end


